# Static data transcribed from the supplied master notes. IDs are stable across options.

GAME = 'Carnival Games MiniGolf'

BASE_ID = 4409088

WORLDS = ("Rah's Revenge",
 'Spook-o-Rama',
 'Amazeon',
 "King's Court",
 'Wild West',
 'Prehistoria',
 'Barn Yard',
 "Pirate's Delight",
 'Fairytella')

HOLES = ('Sky City',
 'Egyptian Way',
 'That Sphinx',
 'Old Toothy',
 "Devil's Brew",
 'Windy Lane',
 'Going Tribal',
 'Big Mouth Juju',
 'Rickety Ride',
 'Crooked Walk',
 "Knight's Gauntlet",
 'Castle Siege',
 'Old #7',
 'Dynamite',
 'Gunslinger',
 "Pterodactyl's Roost",
 'Dino-Mite',
 'Magma Madness',
 'Hog Heaven',
 'Egghead',
 'Old McDoogle',
 'Skull Isle',
 "Pirate's Crossing",
 'Deck Hand',
 'Downhill Slide',
 'Troll Bridge',
 'Flower Power')

MINIGAMES = (('Maze-O-Rama', 2152673920),
 ('Ghoul Hunter', 2152708200),
 ('Jungle Bogey', 2152639232),
 ('Juggles', 2152671712),
 ('Mine Shaft Madness', 2152680872),
 ("Pterodactyl's Run", 2152695976),
 ('The Scrambler', 2152648968),
 ('Cannon Fodder', 2152642344),
 ('G-Nome Project', 2152707388))

PRIZES = ({'id': 0, 'name': 'G-Nome Outfit', 'world': 8, 'kind': 'shop', 'price': 300, 'pieces': 3},
 {'id': 1, 'name': 'Candy Striped Ball', 'world': 8, 'kind': 'shop', 'price': 50, 'pieces': 0},
 {'id': 2, 'name': 'Human G-Nome', 'world': 8, 'kind': 'shop', 'price': 205, 'pieces': 1},
 {'id': 3, 'name': 'Delicious Cupcake', 'world': 8, 'kind': 'shop', 'price': 75, 'pieces': 0},
 {'id': 4, 'name': 'G-Nome Hat', 'world': 8, 'kind': 'shop', 'price': 233, 'pieces': 2},
 {'id': 5, 'name': 'G-Nome Shoes', 'world': 8, 'kind': 'shop', 'price': 175, 'pieces': 1},
 {'id': 6, 'name': 'Falling Star Club', 'world': 8, 'kind': 'club', 'price': 0, 'pieces': 3},
 {'id': 7, 'name': 'G-Nome Necklace', 'world': 8, 'kind': 'shop', 'price': 299, 'pieces': 2},
 {'id': 8, 'name': 'Prehistoric Outfit', 'world': 5, 'kind': 'shop', 'price': 425, 'pieces': 3},
 {'id': 9, 'name': 'Lava Ball', 'world': 5, 'kind': 'shop', 'price': 50, 'pieces': 0},
 {'id': 10, 'name': 'Leaping Lizard', 'world': 5, 'kind': 'shop', 'price': 75, 'pieces': 1},
 {'id': 11, 'name': 'Wacko', 'world': 5, 'kind': 'shop', 'price': 50, 'pieces': 0},
 {'id': 12, 'name': 'Raptor Mask', 'world': 5, 'kind': 'shop', 'price': 250, 'pieces': 2},
 {'id': 13, 'name': 'Dino Tail', 'world': 5, 'kind': 'shop', 'price': 100, 'pieces': 1},
 {'id': 14, 'name': 'Tooth Club', 'world': 5, 'kind': 'club', 'price': 0, 'pieces': 3},
 {'id': 15, 'name': 'Bonehead', 'world': 5, 'kind': 'shop', 'price': 387, 'pieces': 2},
 {'id': 16, 'name': 'Overalls', 'world': 6, 'kind': 'shop', 'price': 200, 'pieces': 2},
 {'id': 17, 'name': 'Egg Ball', 'world': 6, 'kind': 'shop', 'price': 40, 'pieces': 0},
 {'id': 18, 'name': 'Gizzard', 'world': 6, 'kind': 'shop', 'price': 60, 'pieces': 0},
 {'id': 19, 'name': 'Pitchfork of Celebration', 'world': 6, 'kind': 'shop', 'price': 187, 'pieces': 1},
 {'id': 20, 'name': 'Moo Mask', 'world': 6, 'kind': 'shop', 'price': 450, 'pieces': 3},
 {'id': 21, 'name': 'Curly Cue', 'world': 6, 'kind': 'shop', 'price': 150, 'pieces': 1},
 {'id': 22, 'name': 'Hay Club', 'world': 6, 'kind': 'club', 'price': 0, 'pieces': 3},
 {'id': 23, 'name': 'Bullhorn', 'world': 6, 'kind': 'shop', 'price': 250, 'pieces': 2},
 {'id': 24, 'name': 'Pirate Outfit', 'world': 7, 'kind': 'shop', 'price': 275, 'pieces': 2},
 {'id': 25, 'name': 'Cannon Ball', 'world': 7, 'kind': 'shop', 'price': 80, 'pieces': 0},
 {'id': 26, 'name': 'Dem Bones', 'world': 7, 'kind': 'shop', 'price': 125, 'pieces': 1},
 {'id': 27, 'name': 'Pirates Booty', 'world': 7, 'kind': 'shop', 'price': 50, 'pieces': 0},
 {'id': 28, 'name': 'Der Be Pirate', 'world': 7, 'kind': 'shop', 'price': 390, 'pieces': 3},
 {'id': 29, 'name': 'Jolly Roger Cap', 'world': 7, 'kind': 'shop', 'price': 227, 'pieces': 2},
 {'id': 30, 'name': 'Anchor Club', 'world': 7, 'kind': 'club', 'price': 0, 'pieces': 3},
 {'id': 31, 'name': 'Swashbuckla', 'world': 7, 'kind': 'shop', 'price': 190, 'pieces': 1},
 {'id': 32, 'name': 'Medieval Outfit', 'world': 3, 'kind': 'shop', 'price': 342, 'pieces': 3},
 {'id': 33, 'name': 'Mace Ball', 'world': 3, 'kind': 'shop', 'price': 45, 'pieces': 0},
 {'id': 34, 'name': 'The Cat Jester', 'world': 3, 'kind': 'shop', 'price': 150, 'pieces': 1},
 {'id': 35, 'name': 'Dag-gone Dra-gone', 'world': 3, 'kind': 'shop', 'price': 125, 'pieces': 0},
 {'id': 36, 'name': 'Royal Crown', 'world': 3, 'kind': 'shop', 'price': 325, 'pieces': 2},
 {'id': 37, 'name': 'Mr. Shield', 'world': 3, 'kind': 'shop', 'price': 200, 'pieces': 2},
 {'id': 38, 'name': 'Knight Club', 'world': 3, 'kind': 'club', 'price': 0, 'pieces': 3},
 {'id': 39, 'name': 'Boots-O-Armor', 'world': 3, 'kind': 'shop', 'price': 150, 'pieces': 1},
 {'id': 40, 'name': 'Sheriff Outfit', 'world': 4, 'kind': 'shop', 'price': 197, 'pieces': 2},
 {'id': 41, 'name': 'Tumbleweed Ball', 'world': 4, 'kind': 'shop', 'price': 75, 'pieces': 0},
 {'id': 42, 'name': 'Cowbot', 'world': 4, 'kind': 'shop', 'price': 250, 'pieces': 2},
 {'id': 43, 'name': 'Chuck Wagon', 'world': 4, 'kind': 'shop', 'price': 90, 'pieces': 0},
 {'id': 44, 'name': 'Bandito Scarf', 'world': 4, 'kind': 'shop', 'price': 175, 'pieces': 1},
 {'id': 45, 'name': 'Jingle Jangle Boots', 'world': 4, 'kind': 'shop', 'price': 150, 'pieces': 1},
 {'id': 46, 'name': 'Choo Choo Club', 'world': 4, 'kind': 'club', 'price': 0, 'pieces': 3},
 {'id': 47, 'name': '20 Gallon Hat', 'world': 4, 'kind': 'shop', 'price': 400, 'pieces': 3},
 {'id': 48, 'name': 'Egyptian Outfit', 'world': 0, 'kind': 'shop', 'price': 211, 'pieces': 2},
 {'id': 49, 'name': 'Eye of Rah Ball', 'world': 0, 'kind': 'shop', 'price': 50, 'pieces': 0},
 {'id': 50, 'name': "Mummy Don't Dance", 'world': 0, 'kind': 'shop', 'price': 120, 'pieces': 1},
 {'id': 51, 'name': "Tut's Tomb", 'world': 0, 'kind': 'shop', 'price': 90, 'pieces': 0},
 {'id': 52, 'name': "Pharaoh's Hat", 'world': 0, 'kind': 'shop', 'price': 489, 'pieces': 3},
 {'id': 53, 'name': 'Magic Bo Staff', 'world': 0, 'kind': 'shop', 'price': 143, 'pieces': 1},
 {'id': 54, 'name': 'Scepter Club', 'world': 0, 'kind': 'club', 'price': 0, 'pieces': 3},
 {'id': 55, 'name': 'Ramses Mask', 'world': 0, 'kind': 'shop', 'price': 234, 'pieces': 2},
 {'id': 56, 'name': 'Skeleton Outfit', 'world': 1, 'kind': 'shop', 'price': 345, 'pieces': 2},
 {'id': 57, 'name': 'Eye Ball', 'world': 1, 'kind': 'shop', 'price': 90, 'pieces': 1},
 {'id': 58, 'name': 'Jack being Nimble', 'world': 1, 'kind': 'shop', 'price': 150, 'pieces': 2},
 {'id': 59, 'name': 'Baseball Bat', 'world': 1, 'kind': 'shop', 'price': 23, 'pieces': 0},
 {'id': 60, 'name': 'Dr. Boneface', 'world': 1, 'kind': 'shop', 'price': 524, 'pieces': 3},
 {'id': 61, 'name': 'Phalange Feet', 'world': 1, 'kind': 'shop', 'price': 80, 'pieces': 0},
 {'id': 62, 'name': 'Halloween Club', 'world': 1, 'kind': 'club', 'price': 0, 'pieces': 3},
 {'id': 63, 'name': 'Bad Hair Day', 'world': 1, 'kind': 'shop', 'price': 125, 'pieces': 1},
 {'id': 64, 'name': 'Safari Outfit', 'world': 2, 'kind': 'shop', 'price': 300, 'pieces': 2},
 {'id': 65, 'name': 'Jub Jub Ball', 'world': 2, 'kind': 'shop', 'price': 25, 'pieces': 0},
 {'id': 66, 'name': 'Intel-a-gator', 'world': 2, 'kind': 'shop', 'price': 75, 'pieces': 0},
 {'id': 67, 'name': 'Der Sausage Monkey', 'world': 2, 'kind': 'shop', 'price': 110, 'pieces': 1},
 {'id': 68, 'name': 'Adventure Cap', 'world': 2, 'kind': 'shop', 'price': 100, 'pieces': 1},
 {'id': 69, 'name': 'Jungle Foot', 'world': 2, 'kind': 'shop', 'price': 475, 'pieces': 3},
 {'id': 70, 'name': 'Voodoo Club', 'world': 2, 'kind': 'club', 'price': 0, 'pieces': 3},
 {'id': 71, 'name': 'Tiki Mask', 'world': 2, 'kind': 'shop', 'price': 252, 'pieces': 2},
 {'id': 72, 'name': 'Barker Outfit', 'world': None, 'kind': 'barker_shop', 'price': 4, 'pieces': 0},
 {'id': 73, 'name': 'Barker Ball', 'world': None, 'kind': 'barker_shop', 'price': 4, 'pieces': 0},
 {'id': 74, 'name': 'Derby Hat', 'world': None, 'kind': 'barker_shop', 'price': 4, 'pieces': 0},
 {'id': 75, 'name': 'Barker Mustache', 'world': None, 'kind': 'barker_shop', 'price': 4, 'pieces': 0},
 {'id': 76, 'name': 'Barker Bowtie', 'world': None, 'kind': 'barker_shop', 'price': 4, 'pieces': 0},
 {'id': 77, 'name': 'Barker Shoes', 'world': None, 'kind': 'barker_shop', 'price': 3, 'pieces': 0},
 {'id': 78, 'name': 'Cane Club', 'world': None, 'kind': 'barker_shop', 'price': 4, 'pieces': 0},
 {'id': 79, 'name': 'Samurai Face', 'world': 4, 'kind': 'secret', 'price': 50, 'pieces': 0},
 {'id': 80, 'name': 'Florence Mask', 'world': 0, 'kind': 'secret', 'price': 50, 'pieces': 0},
 {'id': 81, 'name': 'Cupid Wings', 'world': 6, 'kind': 'secret', 'price': 50, 'pieces': 0},
 {'id': 82, 'name': 'Dragon Wings', 'world': 1, 'kind': 'secret', 'price': 50, 'pieces': 0},
 {'id': 83, 'name': 'Monkey-On-My-Back', 'world': 2, 'kind': 'secret', 'price': 50, 'pieces': 0},
 {'id': 84, 'name': 'Lion Paws', 'world': 5, 'kind': 'secret', 'price': 50, 'pieces': 0},
 {'id': 85, 'name': 'Rainbow Shoes', 'world': 3, 'kind': 'secret', 'price': 50, 'pieces': 0},
 {'id': 86, 'name': 'Sunday Shoes', 'world': 8, 'kind': 'secret', 'price': 50, 'pieces': 0},
 {'id': 87, 'name': 'Sharkster Shoes', 'world': 7, 'kind': 'secret', 'price': 50, 'pieces': 0})
